INSERT INTO ADDRESS (ID, CITY, STATE, COUNTRY, ZIP_CODE)
    VALUES (-1, 'Fairfield', 'Iowa', 'US', '52556');
    INSERT INTO ADDRESS (ID, CITY, STATE, COUNTRY, ZIP_CODE)
    VALUES (-2, 'Fairfield', 'Iowa', 'US', '52556');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, EMAIL, ADDRESS_ID, PHONE, ENABLED)
    VALUES (-1, 'Admin', 'Admin', 'admin@mum.edu', -1, '+15179189395', 1);

INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, EMAIL, ADDRESS_ID, PHONE, ENABLED)
    VALUES (-2, 'Customer', 'Customer', 'customer@mum.edu', -2, '+15179189395', 1);

INSERT INTO ROLE(ID, ROLE) VALUES(-1, 'ROLE_ADMIN');
INSERT INTO ROLE(ID, ROLE) VALUES(-2, 'ROLE_CUSTOMER');
-- pass = 123456
INSERT INTO USER(ID, EMAIL, PASSWORD, ENABLED) VALUES(-1, 'admin@mum.edu', '$2a$04$pQeYdWnoGFRuxc2GZWMiVuA.lQ345CrC8FDc2cTY4FuRnI4C8rGf.', 1);
INSERT INTO USER_ROLE(ID, USER_ID, ROLE_ID) VALUES(-1, -1, -1);

INSERT INTO USER(ID, EMAIL, PASSWORD, ENABLED) VALUES(-2, 'customer@mum.edu', '$2a$04$pQeYdWnoGFRuxc2GZWMiVuA.lQ345CrC8FDc2cTY4FuRnI4C8rGf.', 1);
INSERT INTO USER_ROLE(ID, USER_ID, ROLE_ID) VALUES(-2, -2, -2);